### ISSUE TITLE
Missing 2.1.0 tag

### ISSUE THREAD

**Issue by wilferrel** [ovenbits/Alexandria#1]
Seems like you guys are missing the tag on your repo? or am I not looking close enough? Tried to do pod install and I get:

```
[!] /usr/bin/git clone https://github.com/ovenbits/Alexandria.git /var/folders/7z/0jyzf27939l_45tmp4rgbf2hzw27vx/T/d20170419-13673-1en747w --template= --single-branch --depth 1 --branch v2.1.0

Cloning into '/var/folders/7z/0jyzf27939l_45tmp4rgbf2hzw27vx/T/d20170419-13673-1en747w'...
warning: Could not find remote branch v2.1.0 to clone.
fatal: Remote branch v2.1.0 not found in upstream origin
```

**Comment by jlandon** [comment]
Hey @wilferrel,

The repo was recently transferred to my personal GitHub account ([jlandon/Alexandria](https://github.com/jlandon/alexandria)), but I hadn't yet updated the podspec in the pod repo. 

Everything should be good to go now. If you still have issues when running `pod install`, try running `pod repo update` first, then `pod install` should work. Let me know if for some reason that still doesn't work for you. Thanks for reaching out!

**Comment by wilferrel** [comment]
Awesome thanks!
